# Generated by Django 2.0.6 on 2018-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='정가')),
                ('discount_price', models.PositiveIntegerField(default=True, verbose_name='할인금액')),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=True, related_name='products', to='product.Category')),
            ],
        ),
    ]
