# Generated by Django 2.0.7 on 2018-08-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='ParentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PARENT_CATEGORY_side', '밑반찬'), ('PARENT_CATEGORY_soup', '국,찌개'), ('PARENT_CATEGORY_main', '메인반찬'), ('PARENT_CATEGORYSIDE_child', '아이반찬'), ('PARENT_CATEGORYSIDE_regular', '정기반찬'), ('PARENT_CATEGORYSIDE_simple', '간편식'), ('PARENT_CATEGORYSIDE_snack', '간식'), ('PARENT_CATEGORYSIDE_brand', '브랜드관')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='정가')),
                ('discount_price', models.PositiveIntegerField(default=0, verbose_name='할인금액')),
                ('sale_price', models.PositiveIntegerField(default=0, verbose_name='판매가격')),
                ('point_amount', models.IntegerField(default=0, verbose_name='적립될 포인트')),
                ('type', models.CharField(blank=True, max_length=300)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('weight', models.IntegerField(default=0)),
                ('materials', models.TextField()),
                ('alert_allergy', models.TextField()),
                ('stock', models.IntegerField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('delivery_days', models.CharField(blank=True, choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], max_length=20, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.Category')),
                ('related_products', models.ManyToManyField(blank=True, to='product.Product', verbose_name='related products')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(max_length=250, on_delete=django.db.models.deletion.CASCADE, to='product.ParentCategory'),
        ),
    ]
