# Generated by Django 2.1 on 2018-08-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('product',),
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='할인율'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='name',
            field=models.CharField(choices=[('side-dish', '밑반찬'), ('soup', '국,찌개'), ('main-courses', '메인반찬'), ('kids', '아이반찬'), ('set-of-side', '정기반찬'), ('fresh', '간편식'), ('refreshment', '간식')], max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
