# Generated by Django 2.0.7 on 2018-08-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180805_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(default=0, verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='product',
            name='point_amount',
            field=models.IntegerField(default=0, verbose_name='적립될 포인트'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.PositiveIntegerField(default=0, verbose_name='판매가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='정가'),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
