# Generated by Django 2.1 on 2018-08-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail_url6',
            field=models.URLField(blank=True, null=True),
        ),
    ]
