# Generated by Django 2.0.6 on 2018-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180728_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='price',
            name='discount_price',
            field=models.PositiveIntegerField(default=0, verbose_name='할인금액'),
        ),
        migrations.AddField(
            model_name='price',
            name='point_amount',
            field=models.IntegerField(default=0, verbose_name='적립될 포인트'),
        ),
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='정가'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
