# Generated by Django 2.0.7 on 2018-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180728_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.CharField(blank=True, choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], max_length=20, null=True),
        ),
    ]
