# Generated by Django 2.1 on 2018-08-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180807_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',)},
        ),
    ]
