# Generated by Django 2.1 on 2018-08-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(default='', max_length=6)),
                ('contact_phone', models.CharField(default='', help_text='필수입력, {3}-{4}-{4}형식만 허용', max_length=15, verbose_name='전화번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
