# Generated by Django 2.1 on 2018-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, help_text='필수입력', null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_phone',
            field=models.CharField(default='', help_text='필수입력, {3}-{4}-{4}형식만 허용', max_length=150, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(help_text='필수입력', max_length=100, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jibun_address',
            field=models.CharField(blank=True, help_text='선택입력', max_length=100, verbose_name='지번 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='road_address',
            field=models.CharField(blank=True, help_text='선택입력', max_length=100, verbose_name='도로명 주소'),
        ),
    ]
