# Generated by Django 2.0.7 on 2018-07-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='user_addresses', to='members.Address'),
        ),
    ]
