# Generated by Django 2.0.7 on 2018-07-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180730_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
