# Generated by Django 2.1 on 2018-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180821_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact_phone',
            field=models.CharField(default='', help_text='필수입력, {3}-{4}-{4}형식만 허용', max_length=15, primary_key=True, serialize=False, verbose_name='전화번호'),
        ),
    ]
