# Generated by Django 2.0.6 on 2018-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20180728_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
