# Generated by Django 2.1 on 2018-08-21 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180814_1751'),
        ('cart', '0002_auto_20180817_1800'),
    ]

    operations = [
    ]
